[build]
  publish = "public"
  functions = "functions"
  command = "npm install --prefix functions"

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

[[headers]]
  for = "/data/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200