[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
