[build]
  publish = "public"
  functions = "functions"
  command = "npm install"

# Veri dosyasına public klasörüyle beraber yayınlanmasını sağla
[[plugins]]
  package = "@netlify/plugin-local-install-core"

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200